/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface AppTabs {
    }
    interface PageChat {
        "name": string;
    }
    interface PageChats {
    }
    interface PageSettings {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppTabsElement extends Components.AppTabs, HTMLStencilElement {
    }
    var HTMLAppTabsElement: {
        prototype: HTMLAppTabsElement;
        new (): HTMLAppTabsElement;
    };
    interface HTMLPageChatElement extends Components.PageChat, HTMLStencilElement {
    }
    var HTMLPageChatElement: {
        prototype: HTMLPageChatElement;
        new (): HTMLPageChatElement;
    };
    interface HTMLPageChatsElement extends Components.PageChats, HTMLStencilElement {
    }
    var HTMLPageChatsElement: {
        prototype: HTMLPageChatsElement;
        new (): HTMLPageChatsElement;
    };
    interface HTMLPageSettingsElement extends Components.PageSettings, HTMLStencilElement {
    }
    var HTMLPageSettingsElement: {
        prototype: HTMLPageSettingsElement;
        new (): HTMLPageSettingsElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "app-tabs": HTMLAppTabsElement;
        "page-chat": HTMLPageChatElement;
        "page-chats": HTMLPageChatsElement;
        "page-settings": HTMLPageSettingsElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface AppTabs {
    }
    interface PageChat {
        "name"?: string;
    }
    interface PageChats {
    }
    interface PageSettings {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "app-tabs": AppTabs;
        "page-chat": PageChat;
        "page-chats": PageChats;
        "page-settings": PageSettings;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-tabs": LocalJSX.AppTabs & JSXBase.HTMLAttributes<HTMLAppTabsElement>;
            "page-chat": LocalJSX.PageChat & JSXBase.HTMLAttributes<HTMLPageChatElement>;
            "page-chats": LocalJSX.PageChats & JSXBase.HTMLAttributes<HTMLPageChatsElement>;
            "page-settings": LocalJSX.PageSettings & JSXBase.HTMLAttributes<HTMLPageSettingsElement>;
        }
    }
}
